apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-uploader-data
  labels:
    app: file-uploader
  namespace: file-uploader
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
