apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-uploader-data
  labels:
    app: file-uploader
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  dataSource:
    name: file-uploader-data-snapshot
    kind: VolumeSnapshot 
    apiGroup: snapshot.storage.k8s.io 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
